# Generated by Django 2.2 on 2020-06-02 07:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
