# Generated by Django 2.2 on 2020-06-02 09:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200602_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='blogImages'),
        ),
    ]
